name: Main

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      exclude_swift_versions: |
        [
            { "swift_version": "5.8"},
            { "swift_version": "5.9"},
            { "swift_version": "5.10"}
        ]
      swift_flags: ""
      swift_nightly_flags: ""
